###
GET http://localhost:3000/api/cardapio?category=do dia
Content-Type: 'application/json'
###

###
POST http://localhost:3000/api/cardapio
Content-Type: 'application/json'

{
    "category": "do dia",
    "name": "Bife à Milanesa",
    "description": "Clássico bife à milanesa servido com arroz, macarrão ao dente, batata frita e uma salada fresca.",
    "image": "https://www.shutterstock.com/image-photo/yogyakarta-indonesia-oct-142021-coca-600nw-2534402125.jpg",
    "sizes": [
        {
            "type": "Mini",
            "price": 18
        },
        {
            "type": "Médio",
            "price": 20
        }
    ]
}

###

###
GET http://localhost:3000/api/payment/cardbrand
Content-Type: 'application/json'

###