import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Roboto } from "next/font/google";
import "./globals.css";


// Context
import { MenuContextProvider } from "../../context/MenuContext";
import { CartContextProvider } from "../../context/cartContext";
import { AuthGlobalContext } from "@/components/SessionWrapper/sessionWrapper";

// Components
import { Navbar } from "@/components/globalComponents/navbar/navBar";
import { CartSideBar } from "@/components/globalComponents/navbar/CartSidebar/cartSideBar";
import { SideMenu } from "@/components/globalComponents/sideMenu/SideMenuContainer";
import { Footer } from "@/components/globalComponents/footer/footer";


import { ToastContainer } from "react-toastify";


const roboto = Roboto({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ['400', '600']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} antialiased'}`}>
        <AuthGlobalContext>
          <ToastContainer />
          <CartContextProvider>
            <MenuContextProvider>
              <SideMenu />
              <Navbar />
              <CartSideBar />
              {children}
              <Footer />
            </MenuContextProvider>
          </CartContextProvider>
        </AuthGlobalContext>
      </body>
    </html>
  );
}

