import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Roboto } from "next/font/google";
import "./globals.css";


// Components

import { Navbar } from "@/components/layout/navbar/navBar";
import { SideMenu } from "@/components/layout/sideMenu/SideMenuContainer";

import { MenuContextProvider } from "../../context/MenuContext";
import { CartSideBar } from "@/components/layout/navbar/CartSidebar/cartSideBar";
import { CartContextProvider } from "../../context/cartContext";
import { Footer } from "@/components/layout/footer/footer";

import SessionWrapper from "@/components/layout/SessionWrapper.tsx";
import { LoadingPage } from "@/components/layout/fallbackContainer";
import { ToastContainer } from "react-toastify";


const roboto = Roboto({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ['400', '600']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} antialiased'}`}>
        <LoadingPage>
          <ToastContainer />
          <CartContextProvider>
            <MenuContextProvider>
              <SideMenu />
              <Navbar />
              <CartSideBar />
              {children}
              <Footer />
            </MenuContextProvider>
          </CartContextProvider>
        </LoadingPage>
      </body>
    </html>
  );
}
