import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Roboto, Baloo_2, Fredoka } from "next/font/google";
import "./globals.css";


// Context
import { MenuContextProvider } from "../../context/MenuContext";
import { ToggleCartContextProvider } from "../../context/toggleCartContext";
import { AuthGlobalContext } from "@/components/SessionWrapper/sessionWrapper";
import { CartContextProvider } from "../../context/cartContext";
import { QuantityContextProvider } from "../../context/quantityContext";

// Components
import { Navbar } from "@/components/globalComponents/navbar/navBar";
import { CartSideBar } from "@/components/globalComponents/navbar/CartSidebar/cartSideBar";
import { SideMenu } from "@/components/globalComponents/sideMenu/SideMenuContainer";
import { Footer } from "@/components/globalComponents/footer/footer";


import { ToastContainer } from "react-toastify";
import { MessagesContextProvider } from "../../context/messagesContext";
import { WarningModalProvider } from "../../context/warningModalContext";
import { AdminContextProvider } from "../../context/isAdminContext";
import Head from "next/head";


const baloo = Baloo_2({ subsets: ['latin'], weight: '400' })

const free = Fredoka({ subsets: ['latin'], weight: ['400'] })

const roboto = Roboto({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ['400', '600']
})

export const metadata: Metadata = {
  title: "Paraíso da gastronomia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-BR">
      <Head>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="public/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="public/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="public/favicon-16x16.png" />
      </Head>
      <body className={`${baloo.className} antialiased}`}>


        <MessagesContextProvider>
          <WarningModalProvider>
            <AdminContextProvider>
              <AuthGlobalContext>
                <ToastContainer />
                <ToggleCartContextProvider>
                  <QuantityContextProvider>
                    <MenuContextProvider>
                      <CartContextProvider>
                        <SideMenu />
                        <Navbar />
                        <CartSideBar />
                        {children}
                        <Footer />
                      </CartContextProvider>
                    </MenuContextProvider>
                  </QuantityContextProvider>
                </ToggleCartContextProvider>
              </AuthGlobalContext>
            </AdminContextProvider>
          </WarningModalProvider>
        </MessagesContextProvider>
      </body>
    </html>
  );
}

